### ISSUE TITLE
index out of bounds - hog::cell_histograms always computes signed gradient orientation

### ISSUE THREAD

**Issue by gaborigloi** [PistonDevelopers/imageproc#127]
I think `hog::cell_histograms` does not take into account `HogOptions.signed` - the gradient orientation `d` is not normalized to the [0, pi) interval when we compute unsigned gradients. When we subsequently compute the orientation bin indices from `d / interval`, the assumption of `Interpolation::from_position_wrapping` (that the left index is within bounds) will be violated. This resulted in 'index out of bounds' when I tried to compute the HOG descriptor of an image with unsigned gradients: I specified 9 unsigned gradient orientation bins but the indices in `o_inter` were `{17, 0}`  when this happened.

I think this can be fixed by inserting something like
```rust
if !spec.options.signed && d >= f32::consts::PI {
   d = d - f32::consts::PI;
}
```
before we calculate `o_inter`. The `=` in `>=` is again important to avoid index out of bounds error by ensuring that `d` is strictly less than pi.

**Comment by theotherphil** [comment]
Thanks for the bug report. I'll fix and add a test soon.
