### ISSUE TITLE
Document row/column-major order

### ISSUE THREAD

**Issue by jonysy** [PistonDevelopers/imageproc#136]
Functions and methods that require passing in a matrix represented as a slice, such as [`filter3x3`](http://docs.piston.rs/imageproc/imageproc/filter/fn.filter3x3.html) and [`Kernel::new`](http://docs.piston.rs/imageproc/imageproc/filter/struct.Kernel.html#method.new), are currently missing documentation regarding [how](https://en.wikipedia.org/wiki/Row-major_order) the data should be arranged.

#### Example

Should the `kernel` argument for `filter3x3` be [a<sub>11</sub>, a<sub>12</sub>, a<sub>13</sub>, a<sub>21</sub>, a<sub>22</sub>, ..] \(row-major order) or [a<sub>11</sub>, a<sub>21</sub>, a<sub>31</sub>, a<sub>21</sub>, ..] \(column-major order).

Cheers :)

**Comment by theotherphil** [comment]
Good point. Patches welcome :-) Otherwise I'll fix within the next day or two.

**Comment by jonysy** [comment]
> Patches welcome :-)

Are the functions traversing the matrix (slice) by rows or columns?

Thanks in advance

**Comment by theotherphil** [comment]
They're all row-major.
