### ISSUE TITLE
Add functions for adding noise to images

### ISSUE THREAD

**Issue by theotherphil** [PistonDevelopers/imageproc#15]
Should include at least Gaussian, shot and salt-and-pepper noise.

**Comment by theotherphil** [comment]
Added Gaussian and salt-and-pepper noise. Not bothering with shot noise for now as the rand crate doesn't yet support Poisson distributions.

**Comment by bvssvni** [comment]
Maybe we could write a Poisson distribution in its own library?

**Comment by theotherphil** [comment]
I was planning on just ignoring this for now until support for Poisson distributions appears in rand. For my purposes (generating synthetic views of a given image), I'm happy to just use Gaussian noise. If it turns out there's someone with a current use for this I'll have a look at adding support myself.
