### ISSUE TITLE
Add support for drawing curves

### ISSUE THREAD

**Issue by huderlem** [PistonDevelopers/imageproc#151]
It would be nice to have bezier curve support (and maybe some other curve variants) in the `imageproc::drawing` crate.  I'd like to take a stab at implementing this.

**Comment by theotherphil** [comment]
That sounds like a good addition, thanks. I'll be slow (or unable) to reply to anything over the next few days as I currently have very patchy internet access.

**Comment by theotherphil** [comment]
https://github.com/PistonDevelopers/imageproc/pull/152
