### ISSUE TITLE
Drawing TTF fonts/text

### ISSUE THREAD

**Issue by mhsjlw** [PistonDevelopers/imageproc#154]
It would be interesting to look at ways to draw TTF fonts (or just any text) onto supported images. Let me know what you think!

Take a look at https://github.com/dylanede/rusttype as well

**Comment by theotherphil** [comment]
Thanks for the suggestion.

What are you proposing we add? I don't think we should attempt to tackle font rendering in this library directly, but maybe we could add a wrapper around e.g. the rusttype library you linked.

**Comment by mhsjlw** [comment]
Yes, my proposal is to add a text rendering functionality, possibly using the rusttype library I mentioned

This could be used for adding text watermarks or captions to images for example

**Comment by theotherphil** [comment]
I agree that this would be a nice thing to have.

**Comment by mhsjlw** [comment]
I think the best way might be generating a bitmap with rusttype then interpolating it with an imageproc image. Is there any place where we can talk about this informally?

**Comment by theotherphil** [comment]
Not currently. I could set up a gitter chat room for this repo if you like, or use any other room/UTC channel you suggest.

**Comment by theotherphil** [comment]
I can't edit messages on my phone. s/UTC/IRC/ !

**Comment by mhsjlw** [comment]
I think Gitter would work, if you're up for it

**Comment by theotherphil** [comment]
Sure. I'll sort it out this weekend - I don't have a lot of spare time during the week.

**Comment by theotherphil** [comment]
I just tried to do this, but gitter wouldn't let me create a room for either this project or my fork of it, and I'm not sure why. "Allow private repo access on the GitHub org or make your org membership public. We are forbidden from seeing what's going on". My org membership _is_ public, as far as I can see. I've not attempted to create a gitter room before, and I'm off to a bad start!

**Comment by bvssvni** [comment]
I've created a new chat room on gitter: https://gitter.im/PistonDevelopers/imageproc

**Comment by theotherphil** [comment]
Brilliant, thank you!

**Comment by mhsjlw** [comment]
See #157

**Comment by theotherphil** [comment]
Closed by https://github.com/PistonDevelopers/imageproc/pull/157
