### ISSUE TITLE
Otsu Level implementation incorrect?

### ISSUE THREAD

**Issue by nliberg** [PistonDevelopers/imageproc#175]
The results returned by `imageproc::contrast::otsu_level` are not at all consistent with those from the python library skimage (see [`skimage.filters.threshold_otsu`](http://scikit-image.org/docs/dev/api/skimage.filters.html#skimage.filters.threshold_otsu)). Eg. when given one of my sample images as input the imageproc function returned an Otsu level of 86 whereas the skimage function returned 171. The value range being 0-255 this is a huge difference. The results differ (although much less so) for the sample image used in the rust code test case too.

I tried to reimplement the code given on [this page](http://www.labbookpages.co.uk/software/imgProc/otsuThreshold.html#java) in Rust (see below) and I ended up with the same result as the python library which makes me wonder whether there's something wrong with the imageproc implementation.

For reference, here's my translation into Rust of that Java code:
```rust
// Based on http://www.labbookpages.co.uk/software/imgProc/otsuThreshold.html#java
pub fn otsu_level(image: &GrayImage) -> u8 {
    // calculate histogram
    let hist = histogram(image);  // from imageproc
    let width = image.width();
    let height = image.height();

    // total number of pixels
    let total = width * height;

    let sum = hist.iter().enumerate()
        .fold(0f64, |sum, (t, h)| sum + (t as u32 * h) as f64);

    let mut sumB = 0f64;
    let mut wB = 0u32;
    let mut wF = 0u32;

    let mut varMax = 0f64;
    let mut threshold = 0u8;

    for (t, h) in hist.iter().enumerate() {
        // weight background
        wB = wB + h;
        if wB == 0 {
            continue
        };

        // weight foreground
        wF = total - wB;
        if wF == 0 { break };

        sumB += (t as u32 * h) as f64;

        // mean background
        let mB = sumB / (wB as f64);

        // mean foreground
        let mF = (sum - sumB) / (wF as f64);

        // calculate between class variance
        let varBetween = (wB as f64) * (wF as f64) * (mB - mF).powi(2);

        // check if new maximum found
        if varBetween > varMax {
            varMax = varBetween;
            threshold = t as u8;
        }
    }
    threshold
}

```

**Comment by akonneker** [comment]
I wrote that from scratch... and I didn't test it that thoroughly, so it's certainly possible there is an error. I was comparing against the matlab implementation, as well, although I wouldn't expect that to matter much. I'll take a closer look at it this weekend.

**Comment by nliberg** [comment]
Great. Thanks a lot.
In case it's of any help: assuming I recall the details of my test correctly, for the input image that resulted in 171 using skimage the two variables `otsu` and `otsu2` in the imageproc code were set to 0 and 171 respectively which resulted in an average of 86. I can't say that I fully understand the `otsu_level` code in imageproc, but this lead me to believe that perhaps these variables are sometimes not both properly initialized.

**Comment by akonneker** [comment]
So I think the only difference in the code is that mine takes into account the possibility that a run of certain levels will produce the same between-class variance, and it will find the midpoint of the run.

It's not doing it correctly, though, since it averages the threshold values no matter what. So it will be wrong in cases that have an unambiguous optimal level. I just need to tweak that, or maybe remove it entirely. Looking back, if the result is ambiguous, why not just take the lowest value, like yours does?

Your code has a more functional flair to it than mine, though. Is there any reason to believe that using iterators/fold will produce more performant code when compiled? If so, you can submit a pull request and we'll swap them out.

Thanks again for pointing out the error.

**Comment by theotherphil** [comment]
Thanks for the bug report @nliberg, and comments @akonneker. As this has been sitting open for a while now I'll fix it today.
