### ISSUE TITLE
Initial crate release

### ISSUE THREAD

**Issue by theotherphil** [PistonDevelopers/imageproc#18]
We don't have to make this polished, just less rough than the code is now.

* ~~Try to reduce signature bloat a little. Unfortunately I think we're stuck with the I: 'static, I::Pixel: 'static, <I::Pixel as Pixel>::Subpixel: + 'static spam for now (but I'd be very happy to be shown wrong).~~
* Check the TODOs for anything easily fixable.
* Profile performance. I've still not looked at this, but I fear the performance is pretty woeful. If we're 2x slower than, say, OpenCV that's fine for now. If we're 100x slower not so much.
* ~~Make the existing functions nicer to call, probably with a mix of functions taking loads of options and functions providing sensible defaults for some of those options that forward to the verbose ones.~~ 
* ~~Stop spamming everything directly into master. I'll create a fork and move my future commits to go via pull requests.~~
* ~~Set up continuous integration. Anyone want to help with this one?~~
* Better readme - give usage examples, and briefly discuss future plans and how to contribute.
* ~~Add a license.~~
* ~~Build on stable.~~

**Comment by theotherphil** [comment]
I've added pub type VecBuffer<P: Pixel> = ImageBuffer<P, Vec<P::Subpixel>>; to my fork of this crate, which lets me tidy a lot of noise from function signatures. However, it also produces a (spurious in this case) compiler warning. I'm not sure whether the extra neatest is worth adding a compiler warning. Ideally I'd like to just disable the warning in this one place, but I can't see how I'd do that.

**Comment by theotherphil** [comment]
Function signatures are now looking a bit nicer: https://github.com/PistonDevelopers/imageproc/pull/19

**Comment by softprops** [comment]
look forward to this being a published crate

**Comment by theotherphil** [comment]
I was holding off on publishing because I expect everything to be very unstable for a while and didn't want to annoy everyone with constant breaking changes.

However, if there's demand for this to be in cargo (with the understanding that breaking changes are highly likely) then I can publish this weekend.

**Comment by softprops** [comment]
I just started exploring the landscape of image processing options in (stable) rust on crates.io. I found and started working with your image crate but the image ops provided were pretty minimal. I was looking for gradient color map support. I saw there was a color map option in that crate but it wasn't clear how to map or create gradients. That's how I happened to stumble on this repo.

I wouldn't mind the breaking changes in pre 1.0 releases. I'd expect them! As that would be the time users can try things out and learn what feels right and what feels wrong :)

**Comment by theotherphil** [comment]
Ok, cool. One stumbling block is that this library currently only builds on nightly rust. I've created https://github.com/PistonDevelopers/imageproc/issues/83 to fix this, and I'll have a look at this soon.

**Comment by theotherphil** [comment]
BTW @softprops, what do you mean by gradient colour maps? Googling produced a few mentions of photoshop, but no definitions I could see.

**Comment by theotherphil** [comment]
https://crates.io/crates/imageproc/

**Comment by theotherphil** [comment]
I've added @bvssvni  as a crate owner.

**Comment by tafia** [comment]
nice!

**Comment by softprops** [comment]
@theotherphil here's a link that may help describe what im trying to figure out how to do http://www.imagemagick.org/Usage/color_mods/#duotone

The idea is to take an image, grayscale it, create a 2 color gradient and somehow map those colors to the grayscale creating a duotone effect.

**Comment by theotherphil** [comment]
Thanks, makes sense. I assume you're after something matching what ImageMagick can do, and I've created https://github.com/PistonDevelopers/imageproc/issues/96. If this isn't quite what you were after then please comment there.

**Comment by softprops** [comment]
Thanks. Will do!

**Comment by bvssvni** [comment]
I added the PistonCollaborator team as owners on crates.io. Updated [Piston overview](https://github.com/PistonDevelopers/piston/wiki/Piston-overview) on the wiki. Imageproc is now listed under "Standalone libraries".

**Comment by theotherphil** [comment]
Great, thanks!
