### ISSUE TITLE
No obvious way to create a rectangle

### ISSUE THREAD

**Issue by archer884** [PistonDevelopers/imageproc#180]
Looks like there's an entire source file set aside for building rectangles, except that there is not an accessible constructor in it for either  `Rect` or `RectPosition`--which means, since they build one another, that you can't actually build either one.

I may have missed something, of course.

Is there a way to build a rectangle? If not, is this intended?

**Comment by theotherphil** [comment]
The unit tests in rect.rs have plenty of examples, but the API isn't terribly intuitive. For example:

```
  let r = Rect::at(5, 5).of_size(6, 6);
```

This seemed like a good idea at the time, as I've previously had to waste lots of my time looking up whether e.g. ```SomeRectType(a, b, c, d)``` has width c and height d or maybe inclusive rightmost x-coordinate c or exclusive rightmost x-coordindate c, etc.

I'll make the docs clearer by adding that example to the docs for both Rect and RectPosition. Do you think that's enough? If not, which methods would you rather see?

**Comment by theotherphil** [comment]
I've updated the docs here: https://github.com/PistonDevelopers/imageproc/pull/181

**Comment by archer884** [comment]
@theotherphil Thanks a lot, that really clears up my confusion.
