### ISSUE TITLE
Line Iterators

### ISSUE THREAD

**Issue by e-maschio** [PistonDevelopers/imageproc#230]
In a little personal project of mine, I constantly need to access pixels of a line. Since I'm using this crate, I thought it would be good to bring this feature to discussion.

There's a class _LineIterator_ in OpenCV which uses Bresenham algorithm to find the points in a line, then return the pixels. I see that in the _draw\_line\_segment()_ we already use the same algorithm, so the implementation should not differ that much. I'm pretty new to Rust though so I'm not sure if it's the best way to implement, specially with mutable pixels. Thoughts?

**Comment by theotherphil** [comment]
This sounds like a nice addition to the library. The easiest approach is probably to write an iterator which returns points, and then optionally wrap this and an image reference in a struct which references pixel references. I'm not sure of the performance impact of this (i.e. whether we can trust everything to get inlined), but the drawing code was never designed to be massively performant anyway. I should have time to have a go at this today, and I'll let you know how it goes.

**Comment by theotherphil** [comment]
I've committed a BresenhamLineIter which iterates over coordinates. 

I've also got a BresenhamLinePixelIter and BresenhamLinePixelIterMut on my fork of this repo, but I still need to 1. write some tests, 2. convince myself that my use of unsafe is valid in the IterMut type.
