### ISSUE TITLE
Add the ability to output image to a window using some graphics api and probably winit

### ISSUE THREAD

**Issue by lazypassion** [PistonDevelopers/imageproc#277]
Use a graphics api like vulkano or glium to output images to a window(probably using winit) so you can see the output of the different processing algorithms. It would probably help with informal testing of algorithm correctness and faster iteration when writing or using them.

**Comment by theotherphil** [comment]
I agree that this would be useful. I don't want to pull in extra graphics dependencies unconditionally so this should be enabled via a package feature.

I've not felt any need to add this myself because I've not got round to finding a decent debugger setup and so just write files to disk instead. Got any tips on debuggers for Rust?

**Comment by lazypassion** [comment]
I'm also in the same boat. I've tried debugging on vscode and it isn't as satisfactory as the ones found in ides from jetbrains. I've heard clion might be good but I don't have the money to invest into it.

**Comment by theotherphil** [comment]
Thanks for the tip - I'll give the codelldb extension a go.

**Comment by lazypassion** [comment]
Would winit be preferred for the output window or is it ok to use sdl2, although it requires a c library

**Comment by theotherphil** [comment]
My main constraint is that this functionality is hidden behind a feature flag. Beyond that, I'm happy for it to be provided in any sensible form, even if it requires (clearly documented!) extra dependencies or installed libraries.

**Comment by theotherphil** [comment]
That would be cool to have, but it wouldn't totally remove the need for this feature - it's useful to be able to debug an image processing operation somewhere in the middle of a larger piece of code.

**Comment by theotherphil** [comment]
I've seen this example in the image-png repo, which might be a useful starting point:

https://github.com/PistonDevelopers/image-png/blob/master/examples/show.rs
