### ISSUE TITLE
Writing japanese/chinese is not supported

### ISSUE THREAD

**Issue by DoumanAsh** [PistonDevelopers/imageproc#279]
Currently it seems rusttype doesn't support drawing of text that consist of wide characters in languages such as japanese.

For example `おしざー` would result in text being drawn with dummy characters. [Example](https://i.imgur.com/rjuMssc.png)
While other non-latin languages such as russian would be fine.

My font(Segoe Print) definitely should have capacity for japanese as I tried to write using the same font by means of Paint.net

I suspect it is likely to be upstream issue, but just in case I decided to start with rising issue here.

**Comment by HeroicKatora** [comment]
Are you sure that `Segoe Print` is supplying the japanese characters, not a system fallback font? I don't think there are non-latin characters in that font. See [code page](https://docs.microsoft.com/en-us/typography/font-list/segoe-print) information supplied by Microsoft themselves.

**Comment by DoumanAsh** [comment]
Hmmm interesting, I was sure it supplies since Paint.Net had no issues to use it, but thanks for link I'll check it out

**Comment by DoumanAsh** [comment]
It seems to be my misunderstanding, tried MS gothic and it works just fine.
Sorry

**Comment by HeroicKatora** [comment]
That's fine, glad you got it to paint the way you wanted :)
