### ISSUE TITLE
Region labeling panics with large images

### ISSUE THREAD

**Issue by HeroicKatora** [PistonDevelopers/imageproc#285]
# Description of the bug

Calling `region_labelling::connected_components` with an Image of size `(1 << 16, 1 << 16)` and any non-background pixel will panic. For example:

```
extern crate image;
extern crate imageproc;

use image::*;

fn main() {
    let conn = imageproc::region_labelling::Connectivity::Eight;
    let background = Luma([0]);

    let mut buffer = ImageBuffer::<Luma<u8>, _>::new(1u32 << 16, 1u32 << 16);

    for i in 0..1024 {
        buffer.put_pixel(i, i, Luma([1]));
    }

    imageproc::region_labelling::connected_components(&buffer, conn, background);

}
```

# Cause

The cause is arithmetic overflow: 

https://github.com/PistonDevelopers/imageproc/blob/b8296fc3a3f77bf76ded4de7a0fbe42a2969cd09/src/region_labelling.rs#L134

The cast to `usize` should happen before the multiplication. As a consequence labels may then saturate `u64` although a hot-path case distinction could prevent this performance loss. Alternatively, one could panic/error out adaptively only when the labels would actually overflow `u32`.

The panic is only triggered when the actual region count is greater than the overflowed value, and only early when that region is to be merged with another. https://github.com/PistonDevelopers/imageproc/blob/b8296fc3a3f77bf76ded4de7a0fbe42a2969cd09/src/region_labelling.rs#L203

Else, control flow continues until https://github.com/PistonDevelopers/imageproc/blob/b8296fc3a3f77bf76ded4de7a0fbe42a2969cd09/src/region_labelling.rs#L222, where we hit an assertion in `DisjointSetForest::root`.

While we're at it, can the allocations be reworked to be output sensitive? It would be cool to support labeling of very large images with few labels, without allocating `DisjointSetForest` and `output_labels` with much larger memory requirements than are used later. This ties back into keeping labels as `u32` where would only want to allocate at most `u32::max_value()` buckets for the union find.

# Fixes

As discussed above, there are two major possibilities. One is to adaptively continue until we run out of `u32` labels. **This already works correctly in some cases where we overflow!** Consider

```
extern crate image;
extern crate imageproc;

use image::*;

fn main() {
    let conn = imageproc::region_labelling::Connectivity::Four;
    let background = Luma([0]);

    // Overflows size to exactly 0.
    let mut buffer = ImageBuffer::<Luma<u8>, _>::new((1u32 << 16) + 1, (1u32 << 16) + 1);

    buffer.put_pixel(1, 1, Luma([1]));

    imageproc::region_labelling::connected_components(&buffer, conn, background);
}
```

This overflow to give us space for the one label (actually for `(1 << 17) + 1` labels)  we actually want to assign. One could say that bug improved performance here, because we allocate much less memory. We could still panic when the dynamic label number overflows.

The second possibility is to switch to `u64` labels. This is likely going to be slower, more memory intensive and has likely more drawbacks but would be much more simple to implement on top.

Alternative number three: Check that the image size does not overflow `u32` and document that decision.

Of course, one could mix the first and second alternative, or even provide a branching path when the preconditions for the third alternative are met, where the hot path is `u32` such as currently implemented.

**Comment by theotherphil** [comment]
Thanks for the bug report. When writing this library I generally assumed that images would be "small enough", and ignored overflow completely. I'm not yet convinced that it's worth paying a significant increase in complexity or performance cost in order to handle larger images, but I'm willing to have a go and see. We should certainly document the current limitations, and fail fast where possible.

**Comment by HeroicKatora** [comment]
Simply failing fast is probably fine for the moment. Although since it's a potentially silent error there could be users for whom that breaks stuff. But the indexing bug in `image`, which also happens when `width*height` overflows in `u32`, itself seems much more broken and no one has yet noticed it before so it's very likely fine ^^
