### ISSUE TITLE
Feature request: Add image scaling algorithms

### ISSUE THREAD

**Issue by lazypassion** [PistonDevelopers/imageproc#291]

**Comment by theotherphil** [comment]
This is a deliberate omission as the image crate already supports scaling: https://docs.rs/image/0.20.1/image/imageops/fn.resize.html

I'm open to suggestions as to how to flag this in the documentation (and not totally opposed to adding methods here that just forward to those in the image crate).

**Comment by lazypassion** [comment]
oh hahaha, I looked for it in the image crate too, but I didn't look hard enough apparently, just close this issue then. 

Maybe instead of only flagging only that, you should add to the readme that a user should also look in imageops for the image crate before requesting new features and maybe link to it's docs. 

Or just take all of the operations in the imageops in the image crate and just put it all in the imageproc now so that all the available image processing functions are contained in one place, even if it means there are some overlap between crates. I feel like it would be easier even if there aren't that many functions avaiable
