### ISSUE TITLE
Eventually run clippy for this crate?

### ISSUE THREAD

**Issue by lazypassion** [PistonDevelopers/imageproc#299]
Correct warnings from lints within reason(i.e. not every warning is necessarily a problem).

**Comment by theotherphil** [comment]
I'd be happy to recieve a PR for this (but reserve the right to be picky about which lints I agree with! I think I've previously either agreed with or not objected to most lints though).

**Comment by theotherphil** [comment]
I'll do this if you're not already in the middle of fixing up clippy warnings!
