### ISSUE TITLE
Displaying multiple images

### ISSUE THREAD

**Issue by lazypassion** [PistonDevelopers/imageproc#301]
Should displaying multiple images happen in multiple windows or in one window?

**Comment by lazypassion** [comment]
Would you mind the addition of images in the examples folder?

**Comment by theotherphil** [comment]
I’m fine with that in principle, but please don’t add images with a particularly large file size.

**Comment by lazypassion** [comment]
Does it matter to have the ability to name each individual window?

**Comment by theotherphil** [comment]
I think it would be nice to have, but this feature is still useful without it.
