### ISSUE TITLE
Add docs to docs.piston.rs

### ISSUE THREAD

**Issue by theotherphil** [PistonDevelopers/imageproc#47]

**Comment by bvssvni** [comment]
[Here](https://github.com/kmcallister/travis-doc-upload/blob/master/README.md) are the steps.

**Comment by theotherphil** [comment]
Thanks. I just followed the instructions and it doesn't appear to have worked yet. Maybe there's a delay or maybe I'll have to debug later.

**Comment by theotherphil** [comment]
Fixed and working now. Thanks for your help.
