### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by AaronViviano** [PistonDevelopers/imageproc#53]
Hello @theotherphil,
I am interested in helping with this library, as I want to work on a rust based computer vision project, but I'm curious to know what license the library intends to use?

Thank you,
Aaron

**Comment by theotherphil** [comment]
Great! I was intending to use an MIT license, but I'll happily use any other sufficiently permissive license. 

I'll add a license on Sunday or when I get a pull request adding one - whichever is sooner.

**Comment by Phrohdoh** [comment]
MIT. :+1:

**Comment by theotherphil** [comment]
I've added an MIT license.

**Comment by AaronViviano** [comment]
Awesome. Thank you @theotherphil. I like the MIT, as I think its a good choice.

**Comment by AaronViviano** [comment]
One of the things I've been thinking about is if @akonneker needs to agree with the License since they commited code before the license was added or if you, @theotherphil, own the code that @akonneker wrote?

**Comment by theotherphil** [comment]
Good point. I certainly don't claim to own his code! Let's wait to hear back from @akonneker.

**Comment by AaronViviano** [comment]
Sounds good.

**Comment by akonneker** [comment]
You can certainly license my meager contribution as MIT, or whatever else
the consensus is.

**Comment by AaronViviano** [comment]
Sweet. Thank you @akonneker.
