### ISSUE TITLE
Git Ignore File

### ISSUE THREAD

**Issue by AaronViviano** [PistonDevelopers/imageproc#56]
Hello @theotherphil,
I noticed that when compiling the project that Git was picking up a number of unneeded files. So I found a rust ignore file https://github.com/github/gitignore/blob/master/Rust.gitignore which is shown below. I think it would be a good start that we could expand on as needed.
```
# Compiled files
*.o
*.so
*.rlib
*.dll

# Executables
*.exe

# Generated by Cargo
/target/

# Remove Cargo.lock from gitignore if creating an executable, leave it for libraries
# More information here http://doc.crates.io/guide.html#cargotoml-vs-cargolock
Cargo.lock
```

Thoughts?

**Comment by theotherphil** [comment]
Oops, thanks for pointing this out. I have a local .gitignore that for some reason I never committed. I've added it now.

**Comment by AaronViviano** [comment]
Awesome. Thank you.
