### ISSUE TITLE
Project Goals? Non-Goals?

### ISSUE THREAD

**Issue by majkcramer** [PistonDevelopers/imageproc#58]
Could you add some additional lines about Project Goals / Non-Goals to the README.me? Maybe where some help is requested too?

**Comment by theotherphil** [comment]
I don't have a very clear idea of how the library should eventually look, but I'll expand the README a little soon. The open issues give some idea of things that would be good to get some help with.

**Comment by theotherphil** [comment]
I've expanded the README. Hopefully this answers your questions. Thus far nearly all the code is written by one person (me) who's a total newcomer to Rust, so any feedback at all would be great. My use case is to get enough basic image manipulation functions available in Rust to allow me to implement some computer vision algorithms, and it seems like several people want something similar. But I'm open to suggestions about other directions or functionality you might want.
