### ISSUE TITLE
Support building on stable channel

### ISSUE THREAD

**Issue by theotherphil** [PistonDevelopers/imageproc#83]
Might be as easy as just sticking the [bench] tests behind a feature flag.

**Comment by bvssvni** [comment]
Use `cfg_attr` like [this](https://github.com/PistonDevelopers/image/blob/master/src/lib.rs#L8).

**Comment by softprops** [comment]
+1

**Comment by theotherphil** [comment]
Thanks Sven. Doug, I'll sort this one out today.

**Comment by theotherphil** [comment]
Slightly annoying: 

nightly rustc requires: 
```
let mut out = ImageBuffer::<ChannelMap<P, S>, Vec<S>>::new(width, height);
```
stable rustc requires:
```
let mut out = ImageBuffer::<ChannelMap<P, S>>::new(width, height);
```

**Comment by theotherphil** [comment]
Can now build (but not test) on stable, and I've added stable and beta to the CI.
