### ISSUE TITLE
Add image tinting

### ISSUE THREAD

**Issue by theotherphil** [PistonDevelopers/imageproc#96]
@softprops was looking for something like ImageMagick's TintImage function: 
https://github.com/ImageMagick/ImageMagick/blob/master/MagickCore/fx.c.

Visual effects seem like something that should eventually go in a separate crate, but for now it should be pretty easy to add a module containing some ImageMagick-y effects.

**Comment by theotherphil** [comment]
I couldn't make sense of the ImageMagick code, but I guess we're after something like the following: 

```
use image::{
    GrayImage,
    Luma,
    Pixel,
    Rgb,
    RgbImage
};

use definitions::Clamp;

pub fn tint_image(image: &GrayImage, tint_color: Rgb<u8>) -> RgbImage {
    let (width, height) = image.dimensions();
    let mut out = RgbImage::new(width, height);

    for y in 0..height {
        for x in 0..width {
            let tinted = tint(*image.get_pixel(x, y), tint_color);
            out.put_pixel(x, y, tinted);
        }
    }

    out
}

/// Tint a grayscale value with the given color.
pub fn tint(gray: Luma<u8>, color: Rgb<u8>) -> Rgb<u8> {
    let dist_from_mid = (gray[0] as f32 - 128f32).abs();
    let scale_factor = 1f32 - 4f32 * dist_from_mid * dist_from_mid;
    Rgb([gray[0]; 3])
        .map2(&color, |p, q| {
            Clamp::clamp(p as f32 + scale_factor * q as f32)
        })
}

#[cfg(test)]
mod test {

    use super::{
        tint_image
    };
    use utils::{
        load_image_or_panic
    };
    use image::Rgb;
    use test;
    use std::path::Path;

    #[test]
    fn test_tint() {
      let ip = Path::new("./tests/data/elephant.png");
      let tp = Path::new("./tests/data/truth/tintyphant.png");
      let image = load_image_or_panic(&ip).to_luma();
      let eq = tint_image(&image, Rgb([0u8, 0u8, 255u8]));
      let _ = eq.save(&Path::new(tp)).unwrap();
    }
}
```

**Comment by theotherphil** [comment]
@softprops: is this roughly what you were after? I'll tidy this up before committing anyway (it was bodged together in a few minutes), but I'll wait and see if this is actually what's wanted first.

**Comment by softprops** [comment]
Damn you guys are fast! I'm out to town today but I'll give it a spin when i get hone tonight. I think this is perfect for tinting but what I was looking for was something slightly different.

The duotone effect looks something like that but parameterized with 2 colors that form a gradient that could be color mapped to the grayscale pixels.

Here's some visual examples

https://www.google.com/search?q=duotone&client=ms-android-verizon&biw=360&bih=264&prmd=isvn&source=lnms&tbm=isch&sa=X&ved=0ahUKEwjXjaz_lqDKAhWCKj4KHb2hAgYQ_AUIBigB

**Comment by softprops** [comment]
There's a bit more info under the image magic docs about the technique. http://www.imagemagick.org/Usage/color_mods/#duotone

**Comment by theotherphil** [comment]
Cool, thanks. I missed that somehow. I'll add that in the next couple of days.

**Comment by softprops** [comment]
Man. You guys set a high bar for oss friendliness and turnarounds. Keep it up

**Comment by theotherphil** [comment]
Thanks! Sadly the tint function above is rubbish, but I'll add a fixed version tomorrow

**Comment by softprops** [comment]
I'm not sure how compatible it is typewise with this crate but I thought this may be of use http://www.piston.rs/image/image/imageops/colorops/fn.index_colors.html

**Comment by theotherphil** [comment]
imageproc is based on that image crate (the small overlap between this crate and image::imagops will be removed eventually). So the traits and concrete types used are identical. However, it doesn't look like that function gains us too much - implementing our own ColorMap impl for either tinting or duotone would be the same amount of work as writing the functions directly.

**Comment by theotherphil** [comment]
Ok, I may have been a little optimistic when I claimed I'd get this done in a couple of days. Getting aesthetically pleasing results looks like it will require a lot of flexibility in the tinting/blending functions, and writing something decent for this would take a lot longer than I have free this week (and to get the brightness of the tinted image to match the input image we'll need HSL support, which isn't currently available). Also, I'm now more convinced that image effects should go in a separate library. I'll create one this weekend. 

In the meantime, I've written a prototype implementation of tint and colour blending and pushed to a branch of my repo: https://github.com/theotherphil/imageproc/commit/0d9eccbf532ea4b759dd24ceb6a7063feb434d36.

Example output: 

![bphant](https://cloud.githubusercontent.com/assets/1974256/12242868/67e3a66c-b893-11e5-9d44-67a11877a725.png)
![blendphant](https://cloud.githubusercontent.com/assets/1974256/12242875/7092fbf0-b893-11e5-9119-1d767a223b9f.png)

Hopefully this at least gives you a starting point to play around with. I wouldn't count on anything in this area getting released soon, but I'm happy to help with any problems you have getting this to work for your use cases.

**Comment by theotherphil** [comment]
One obvious problem with the current code is that we do non-trivial work for every pixel. So if you need this to be fast we can tweak the code to use a LUT as you suggested.

**Comment by softprops** [comment]
@theotherphil you are a magician! That looks great

**Comment by theotherphil** [comment]
Glad you like it. I've added an example with these colour effects in https://github.com/PistonDevelopers/imageproc/commit/16675470b28c504579b2871d8def91ee4079f197, so will close this issue now.

```
cargo run --example color_effects <your_file_here>
```

It'll create a tinted.png and gradient.png file in the same directory as the input file you provide.
